name: Earnplus
description: Earnplus
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.0.0

flutter:
  uses-material-design: true
